# Generated by Django 3.0.5 on 2020-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(to='main_app.Album'),
        ),
    ]
